#!/bin/bash

while read -r hook; do
    bash "$(dirname "$0")/pre-push.d/$hook"
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-push.d/$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done <<< "$(ls $(dirname "$0")/pre-push.d)"

exit 0
