#!/bin/bash

while read -r hook; do
    bash "$(dirname "$0")/pre-commit.d/$hook"
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done <<< "$(ls $(dirname "$0")/pre-commit.d)"

exit 0
