#!/bin/bash

for hook in "$(dirname "$0")"/pre-push.d/*; do
    bash "${hook}"
    RESULT=$?
    if [[ "${RESULT}" != 0 ]]; then
        echo "$(basename "${hook}") returned non-zero: ${RESULT}, abort commit"
        exit "${RESULT}"
    fi
done

exit 0
